name: "ev_charge_analytics"
version: "1.0.0"
config-version: 2

profile: "ev_charge_analytics"

model-paths: ["models"]

target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  ev_charge_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
